### ISSUE TITLE
Comite Paritario vista Especialistas

### ISSUE THREAD

**Issue by mvegaalarcon** [araucanosland/MDN#106]
Vista para especialistas y gente definida por Katy Vera, para mover ciertos estados de formalización de Electores

**Comment by capradenas** [comment]
### Definiciones

- Los especialistas podrán ver todo Chile, ellos sabrán separar sus sucursales
- Los especialistas podrán marcar ciertas opciones del formulario, a las que solo ellas tendrán privilegios
