### ISSUE TITLE
Datos de Contacto Empresa [16oct]

### ISSUE THREAD

**Issue by mvegaalarcon** [araucanosland/MDN#117]
Generar un Modulo para Datos de Contacto de la Empresa - Punto Atención, debe tener

+Area (Datos seleccionables)
+Cargo (input)
+Rut (input)
+Nombre (input)
+Fono (input)
+Mail (input)

**Comment by sergio-pizarro** [comment]
por debajo debe tener 

- codigo anexo empresa
- rut empresa
- oficinna, ejecutivo
