### ISSUE TITLE
Alerta Fuga Empresa

### ISSUE THREAD

**Issue by mvegaalarcon** [araucanosland/MDN#152]
Copia del Modulo de Camaras, 

Se debe ingresar el rut  nombre de EMpresa y numero d eTrbajadores, y una observación de la posible fuga, para luego tracking

**Comment by capradenas** [comment]
Se Realiza desarrollo, documentación y manual paso a paso

Se adjunta manual paso a paso:
[Manual Paso a Paso - Fuga Empresas.docx](https://github.com/araucanosland/MDN/files/3941387/Manual.Paso.a.Paso.-.Fuga.Empresas.docx)
